#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path(File.dirname(__FILE__) + '/../lib'))

require 'rubygems'
require 'hermann/producer'

topic = 'topic'
brokers = ARGV.first

puts ">> Producer#new('#{topic}', '#{brokers}')"

p = Hermann::Producer.new(topic, brokers)

message = ('b' * 2063) + 'a'

puts ">> Producer#push('#{message}') (#{message.size} bytes)"
p.push(message)

puts "..exiting"
sleep 2

